name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'

      - name: Install dependencies (editable for accurate coverage paths)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[dev,web]'
          python -m pip install build

      - name: Run tests (coverage on 3.12 only)
        run: |
          if [ "${{ matrix.python-version }}" = "3.12" ]; then \
            coverage run -m pytest -q; \
            coverage report -m; \
            coverage xml; \
          else \
            pytest -q; \
          fi

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build package
        run: |
          python -m build

      - name: Upload dist artifacts (single version)
        # Only publish artifacts for pushes to main or tag refs (not PRs)
        if: matrix.python-version == '3.12' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
