name: Desktop Bundles

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read      # Minimal permissions for checkout
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies (dev + web)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[dev,web]'

      - name: Create bundle project
        run: briefcase create

      - name: Build bundle
        run: briefcase build

      - name: Package (if supported)
        run: |
          echo "Attempting package step"
          # Use ad-hoc signing & suppress interactive identity selection in CI
          briefcase package --adhoc-sign --no-input || echo "Package step not implemented for this platform"

      - name: Collect artifacts path
        id: paths
        shell: bash
        run: |
          echo "Listing dist directory"
          ls -R dist || true
          # Upload entire dist for now; expose path via GITHUB_OUTPUT
          echo "distpath=dist" >> "$GITHUB_OUTPUT"

      - name: Upload bundle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}
          path: dist/**/*
          if-no-files-found: warn


