name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # For trusted publishing (if repository is configured) or leave for future use
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build dist (sdist & wheel)
        run: |
          python -m build
          ls -l dist

      - name: Publish to PyPI
        if: success()
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          verbose: true

      - name: Summary
        run: |
          echo "Published tag $GITHUB_REF to PyPI (package version from pyproject)." >> $GITHUB_STEP_SUMMARY
